stages:
  - build
  - test

image-dir1:
  stage: build
  image: docker:20.10.16 
  services:
    - name: docker:20.10.16-dind
      alias: docker
  variables:
    FF_NETWORK_PER_BUILD: "true"
  before_script:
    - apk update && apk add curl
  script:
    - docker run --name testimage -p 80:80 -d nginx
    - docker ps
    - curl http://docker:80

echo-stage:
  stage: test
  image: docker:20.10.16
  script:
    - echo "this is testing commit for child1"
